title: "Tactile Board"
description: "Documentation for the Tactile Board Listener"
remote_theme: pmarsceill/just-the-docs
color_scheme: "light"
search_enabled: false
permalink: pretty

footer_content: "Copyright &copy; 20121-2020 Affective & Cognitive Institute. Distributed by an <a href=\"https://github.com/Suitceyes-Project-Code/Tactile-Board-Listener/blob/master/LICENSE\">MIT license.</a>"